tungbq/AWSHub

README.md
s3/README.md

Add S3 introdution

---

.github/workflows/generate-content.yml
README.md
services.json

[CI] Introduce new workflow to automatically generate content from json definition

---

.github/workflows/generate-content.yml

Using random branch suffix to make sure no conflicts

---

services.json

Add pinpoint placeholder

---

.github/workflows/generate-content.yml

fix: generation content bug 🐛 

---

.github/workflows/release.yml

Fix err in release.yml :bug:

---

services.json

feat: Adding Lamda example

---

.github/workflows/generate-content.yml

Emable automerge in generate-content.yml

---

services.json

feat: adding Appflow

---

services.json

feat: adding AWS Kinesis

---

README.md
ec2/README.md

This PR conatains a new directory for ec2 with its official links and updated README.md

Issue 5 ec2

---

services.json

feat: Add ec2 to services.json

---

.github/workflows/generate-content.yml

feat(ci): only run the generate content workflow if services.json updated

---

services.json

feat: Adding AWS Cloudwatch

---

services.json

feat: Add RDS

---

services.json

Closes: 
[#49](https://github.com/tungbq/AWS-LearningResource/issues/49)
[#69](https://github.com/tungbq/AWS-LearningResource/issues/69)
[#70](https://github.com/tungbq/AWS-LearningResource/issues/70)
[Add controltower service to services.json](https://github.com/tungbq/AWS-LearningResource/commit/03ae0c72051343e18f5d8f879fb42049a807b7d9)
[Add Route53 service to services.json](https://github.com/tungbq/AWS-LearningResource/commit/2f7e11e42a01c3da74794595151454f98aabf145)
[Add Cloudfront service to services.json](https://github.com/tungbq/AWS-LearningResource/commit/74cc231fc80a72014eb54a21d7ef25b391b5cdeb)
Hi [tungbq](https://github.com/tungbq),
just trying to help on these issues by adding services on file [services.json](https://github.com/tungbq/AWS-LearningResource/blob/main/services.j …

Issue#services.json

---

aws-saa-c03/README.md

doc: Add AWS SAA-C03 Official Exam Guide

---

services.json

Closes: #79 
[Add Outposts service to services.json](https://github.com/tungbq/AWS-LearningResource/commit/bcddaf48859f3dd96a32715a9b9b71143c5592e8)
Hi [tungbq](https://github.com/tungbq),
just trying to fixed [issue#79](https://github.com/tungbq/AWS-LearningResource/issues/79), please check it out

Add Outposts service to services.json

---

README.md

Update README.md - aws architectute

---

services.json

Closes: #101 
This pull request enhances the documentation by adding introductory content for AWS ECS. It addresses the following:
- 📝 Introduces ECS introduction content to services.json
- 📁 Creates an 'ecs' folder for ECS-related documentation
- 📝 Adds ECS-specific README.md with official links and a YouTube introduction
- 📝 Updates the main README.md to include a link to the ECS README.md
This update ensures that users have easy access to introductory information about AWS ECS. 🎉
*(E.g.: This pull request improves documentation of area A by adding ....)*

ADD[#101]:AWS ECS Update services.json

---

services.json

Closes: #99
This pull request enhances the documentation by adding introductory content for AWS EKS. It addresses the following:
- 📝 Introduces EKS introduction content to services.json
- 📁 Creates an 'EKS' folder for EKS-related documentation
- 📝 Adds EKS-specific README.md with official links and a YouTube introduction
- 📝 Updates the main README.md to include a link to the EKS README.md
This update ensures that users have easy access to introductory information about AWS EKS. 🎉
*(E.g.: This pull request improves documentation of area A by adding ....)*

Add[#99]: EKS introduction link

---

.github/workflows/link-checker.yml

Closes: #102
This pull request introduces a new GitHub workflow, 'link-checker.yml,' to automate the detection of broken links within the repository. 🔍
This workflow will run weekly and perform the following actions:
- 🕵️‍♀️ Utilize the 'lycheeverse/lychee-action' to scan the repository for broken links.
- 📝 Generate a report summarizing the broken links found.
- 📑 Create an issue titled 'Link Checker Report' containing the generated report.
This enhancement ensures that broken links are identified and addressed promptly, maintaining a seamless user experience. 💯
*(E.g.: This pull request improves documentation of area A by adding ....)*

ADD[#102]:Implement link checker report to check broken link

---

.github/workflows/generate-content.yml

Closes: #48 
This pull request aims to improve the robustness of our GitHub Actions workflow. It addresses the issue where the workflow fails when there are no changes to commit. The proposed changes ensure that the workflow will not fail in such cases, thereby enhancing the stability of our CI/CD pipeline.
1. **Check for Changes:** Before committing, we now check if there are any changes. If there are no changes, we skip the commit step.
2. **Improved Error Handling:** The workflow will no longer fail when there are no changes to commit. This prevents unnecessary workflow failures.
3. **Code Optimization:** The commit step in the workflow has been optimized for better performance.
Here's the key change in code:
```yaml
- name: Commit changes
run: |
git config --local user.email …
```

ADD[#48]:Do not fail the workflow when there is no commit 

---

.github/workflows/markdown-link-checker.yml

ci: Add Markdown Links Checker

---

.github/workflows/markdown-link-checker.yml

ci: update max depth of link checker to 2

---

.github/workflows/link-checker.yml

ci: Update link-checker.yml scheduler

ci: Update link-checker.yml scheduler

---

README.md
TEMPLATE.md
generate-content.sh

Add ID and Youtube hyperlink
Related #134

Add ID and Youtube hyperlink

---

README.md
generate-content.sh

Sort table by service name
#134

Sort table by service name

---

README.md

doc: Add contributing icon 👋
#134

doc: Add contributing icon 👋

---

README.md
services.json

Closes: #142 
AWS Lamda: Duplicated content

AWS Lamda: Duplicated content

---

services.json

Related #146 
docs: fix VPC link

docs: fix VPC link

---

README.md
generate-content.sh

Related #134 
AWS: Add brief introduction with total services info

AWS: Add brief introduction with total services info

---

README.md

docs: Adjust the title
Related #134

docs: Adjust the title

---

README.md
generate-content.sh
services.json

Related #146 
AWS: Add more 5 services to table of content

AWS: Add more 5 services to table of content

---

README.md
docs/troubleshooting.md
generate-content.sh

Related #134 
docs: hyperlink title improvement

docs: hyperlink title improvement

---

README.md

docs: Add AWS intro

---

README.md

docs: Add AWS Architecture content
Part of #134

docs: Add AWS Architecture content

---

README.md

docs: Add whats next
Related #134

docs: Add whats next

---

README.md

docs: main page improvement

---

README.md
generate-content.sh
services.json

docs: Cover more 6 services content
#146

docs: Cover more 6 services content

---

README.md

docs: minor patch

---

README.md

Add AWS Prescriptive Guidance
#134

Add AWS Prescriptive Guidance

---

README.md

Add AWS Hands-on Tutorials
#134

Add AWS Hands-on Tutorials

---

CONTRIBUTING.md

Update project name in CONTRIBUTING.md

Update project name in CONTRIBUTING.md
